// Auto-generated by: supabase gen types typescript --local > lib/types/database.types.ts
// Run this command after every migration to keep this file in sync.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type UserRole = 'student' | 'employer' | 'admin'
export type JobType = 'full-time' | 'part-time' | 'casual' | 'internship'
export type JobStatus = 'draft' | 'active' | 'closed'
export type ApplicationStatus = 'pending' | 'reviewed' | 'shortlisted' | 'rejected'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: UserRole
          full_name: string | null
          avatar_url: string | null
          created_at: string
        }
        Insert: {
          id: string
          role: UserRole
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
        }
        Update: {
          role?: UserRole
          full_name?: string | null
          avatar_url?: string | null
        }
      }
      student_profiles: {
        Row: {
          user_id: string
          tafe_campus: string | null
          course: string | null
          graduation_year: number | null
          bio: string | null
          skills: string[]
          resume_url: string | null
          availability: JobType | null
          is_visible: boolean
        }
        Insert: {
          user_id: string
          tafe_campus?: string | null
          course?: string | null
          graduation_year?: number | null
          bio?: string | null
          skills?: string[]
          resume_url?: string | null
          availability?: JobType | null
          is_visible?: boolean
        }
        Update: {
          tafe_campus?: string | null
          course?: string | null
          graduation_year?: number | null
          bio?: string | null
          skills?: string[]
          resume_url?: string | null
          availability?: JobType | null
          is_visible?: boolean
        }
      }
      employer_profiles: {
        Row: {
          user_id: string
          company_name: string
          logo_url: string | null
          website: string | null
          industry: string | null
          description: string | null
          location: string | null
          is_verified: boolean
        }
        Insert: {
          user_id: string
          company_name: string
          logo_url?: string | null
          website?: string | null
          industry?: string | null
          description?: string | null
          location?: string | null
          is_verified?: boolean
        }
        Update: {
          company_name?: string
          logo_url?: string | null
          website?: string | null
          industry?: string | null
          description?: string | null
          location?: string | null
          is_verified?: boolean
        }
      }
      job_listings: {
        Row: {
          id: string
          employer_id: string
          title: string
          description: string
          location: string | null
          job_type: JobType
          required_skills: string[]
          salary_min: number | null
          salary_max: number | null
          status: JobStatus
          created_at: string
          expires_at: string | null
        }
        Insert: {
          id?: string
          employer_id: string
          title: string
          description: string
          location?: string | null
          job_type: JobType
          required_skills?: string[]
          salary_min?: number | null
          salary_max?: number | null
          status?: JobStatus
          created_at?: string
          expires_at?: string | null
        }
        Update: {
          title?: string
          description?: string
          location?: string | null
          job_type?: JobType
          required_skills?: string[]
          salary_min?: number | null
          salary_max?: number | null
          status?: JobStatus
          expires_at?: string | null
        }
      }
      applications: {
        Row: {
          id: string
          student_id: string
          job_id: string
          cover_letter: string | null
          status: ApplicationStatus
          created_at: string
        }
        Insert: {
          id?: string
          student_id: string
          job_id: string
          cover_letter?: string | null
          status?: ApplicationStatus
          created_at?: string
        }
        Update: {
          status?: ApplicationStatus
        }
      }
      saved_jobs: {
        Row: {
          student_id: string
          job_id: string
          saved_at: string
        }
        Insert: {
          student_id: string
          job_id: string
          saved_at?: string
        }
        Update: Record<string, never>
      }
    }
  }
}
